{
	'name': 'APEX - Academic Progress and Excellence',
	'version': '18.0.1.0.42',
	'icon': '/aps_sis/static/description/icon.png',
	'category': 'Tools',
	'summary': 'Allow the assigning and tracking of academic tasks such as homework, exams etc.',
	'description': 'APEX - Academic Progress and Excellence. Helps to track student progress. It will work with  EduCat SIS',
	'author': 'APS',
	'license': 'LGPL-3',
	'depends': ['base', 'openeducat_core', 'web', 'mail', 'portal', 'hr'],
	'post_init_hook': 'post_init_hook',
	'data': [
		'security/groups.xml',
		'security/ir.model.access.csv',
		'security/aps_sis_security.xml',
		'data/cron.xml',
		'data/email_templates.xml',
		'data/subject_categories.xml',
		'views/aps_resource_custom_name_views.xml',		
        'views/portal_templates.xml',
		'views/aps_resources_views.xml',
		'views/aps_resource_types_views.xml',
		'views/aps_resource_tags_views.xml',
		'views/aps_assign_students_wizard_views.xml',
		'views/aps_resource_task_views.xml',
		'views/aps_resource_submission_views.xml',
		'views/aps_resource_submission_views_for_students.xml',
		'views/aps_resource_notes_popup_views.xml',
		'views/aps_dashboard_views.xml',
		'views/aps_submission_mass_update_wizard_views.xml',
		'views/aps_resource_mass_update_wizard_views.xml',
		'views/aps_subject_category_views.xml',
		'views/op_program_level_views.xml',
		'views/op_course_views.xml',
		'views/op_subject_views.xml',
		'views/op_faculty_views.xml',
		'views/res_partner_views.xml',
		'views/aps_avatar_views.xml',
		'wizard/aps_avatar_bulk_upload_views.xml',
		'views/aps_time_tracking_views.xml',
		'views/aps_time_tracking_dashboard_views.xml',
		'views/aps_sis_menu.xml',
		'views/op_student_course_views.xml',
		'reports/submission_report.xml',
		'wizard/submission_report_wizard_views.xml'
	],
	'assets': {
		'web.assets_backend': [
            'aps_sis/static/src/lib/chart.js',
			'aps_sis/static/src/js/hide_g2_popup.js',
			'aps_sis/static/src/js/utils/color_utils.js',
			'aps_sis/static/src/js/utils/svg_progress_utils.js',
			'aps_sis/static/src/css/ribbon_styles.css',
			'aps_sis/static/src/css/openeducat.css',
			'aps_sis/static/src/css/ui_tweaks.css',
            'aps_sis/static/src/css/statusbar_colors.css',
			'aps_sis/static/src/css/aps_sis.css',
			'aps_sis/static/src/css/math_formula.css',
			'aps_sis/static/src/css/toc_float.css',
			'aps_sis/static/src/js/percentpie_ranged_widget.js',
			'aps_sis/static/src/xml/percentpie_ranged_field.xml',
			'aps_sis/static/src/js/url_icon_widget.js',
			'aps_sis/static/src/js/recent_submissions_widget.js',            
            'aps_sis/static/src/js/confetti.browser.min.js',            
            'aps_sis/static/src/js/float_sentinel_widget.js',
			'aps_sis/static/src/js/resource_links_widget.js',
			# 'aps_sis/static/src/js/form_notebook_default_page.js',
			'aps_sis/static/src/js/submission_list_score_refresh.js',
            'aps_sis/static/src/js/submission_complete_next_context.js',
            
			'aps_sis/static/src/xml/resource_links_field.xml',
			'aps_sis/static/src/js/clickable_many2many_tags.js',
			'aps_sis/static/src/css/clickable_many2many_tags.css',		
            'aps_sis/static/src/js/parent_child_name_field.js',
			'aps_sis/static/src/xml/parent_child_name_field.xml',			
            'aps_sis/static/src/img/menu_icon.png',
            'aps_sis/static/src/js/breadcrumb_widget.js',
            'aps_sis/static/src/xml/breadcrumb_widget.xml',
            'aps_sis/static/src/js/badge_decorator_widget.js',
            'aps_sis/static/src/xml/badge_decorator_field.xml',
            'aps_sis/static/src/js/math_formula_renderer.js',
            'aps_sis/static/src/js/toc_position_toggle.js',
            'aps_sis/static/src/components/**/*.js',
            'aps_sis/static/src/components/**/*.xml',
            'aps_sis/static/src/components/**/*.scss',
            'aps_sis/static/src/js/image_result_widget.js',
            'aps_sis/static/src/xml/image_result_widget.xml',
            'aps_sis/static/src/css/image_result_widget.css',
            'aps_sis/static/src/js/share_url_widget.js',
            'aps_sis/static/src/js/avatar_bulk_upload.js',
            'aps_sis/static/src/xml/avatar_bulk_upload.xml',
            'aps_sis/static/src/js/avatar_selector.js',
            'aps_sis/static/src/xml/avatar_selector.xml',
            'aps_sis/static/src/js/avatar_systray_patch.js',
            'aps_sis/static/src/xml/avatar_systray.xml',
		],
	},
	'installable': True,
	'application': False,
}
