{
	'name': 'APS SIS Resources',
	'version': '18.0.1.0.5',
	'icon': '/aps_sis/static/description/icon.png',
	'category': 'Tools',
	'summary': 'Manage APS resources and types (URLs, descriptions).',
	'description': 'APS - Academic Positioning System / Academic Progress System. Helps to track student progress. It will work with  EduCat SIS',
	'author': 'APS',
	'license': 'LGPL-3',
	'depends': ['base', 'openeducat_core', 'web', 'mail', 'portal'],
	'post_init_hook': 'post_init_hook',
	'data': [
		'security/groups.xml',
		'security/ir.model.access.csv',
		'security/aps_sis_security.xml',
		'views/portal_templates.xml',
		'views/aps_resources_views.xml',
		'views/aps_resource_types_views.xml',
		'views/aps_assign_students_wizard_views.xml',
		'views/aps_resource_task_views.xml',
		'views/aps_resource_submission_views.xml',
		'views/aps_resource_submission_views_for_students.xml',
		'views/op_program_level_views.xml',
		'views/op_course_views.xml',
		'views/op_subject_views.xml',
		'views/op_faculty_views.xml',
		'views/res_partner_views.xml',
		'views/aps_sis_menu.xml',
		'views/op_student_course_views.xml',
		'reports/submission_report.xml',
		'wizard/submission_report_wizard_views.xml',
	],
	'assets': {
		'web.assets_backend': [
			'aps_sis/static/src/js/hide_g2_popup.js',
			'aps_sis/static/src/css/ribbon_styles.css',
			'aps_sis/static/src/css/openeducat.css',
			'aps_sis/static/src/css/ui_tweaks.css',
            'aps_sis/static/src/css/statusbar_colors.css',
			'aps_sis/static/src/js/percentpie_ranged_widget.js',
			'aps_sis/static/src/xml/percentpie_ranged_field.xml',
			'aps_sis/static/src/js/url_icon_widget.js',
			'aps_sis/static/src/js/recent_submissions_widget.js',
            'aps_sis/static/src/js/float_sentinel_widget.js',
			'aps_sis/static/src/img/menu_icon.png',
		],
	},
	'installable': True,
	'application': False,
}
