from . import aps_academic_year
from . import aps_academic_term
from . import aps_level
from . import aps_subject_category_tag
from . import aps_subject_category
from . import aps_subject
from . import aps_class
from . import aps_student
from . import aps_student_class
from . import aps_teacher
from . import res_partner_teacher
from . import res_partner_student
