from . import asctt_period
from . import asctt_break
from . import asctt_days_def
from . import asctt_weeks_def
from . import asctt_terms_def
from . import asctt_subject
from . import asctt_teacher
from . import asctt_building
from . import asctt_classroom
from . import asctt_grade
from . import asctt_class
from . import asctt_group
from . import asctt_lesson
from . import asctt_card
from . import asctt_classroom_supervision
from . import asctt_flat_row
from . import asctt_class_subject_minutes
from . import asctt_dashboard
from . import asctt_import_wizard
