from . import aps_avatar
from . import aps_media
from . import aps_time_tracking
from . import ai_feedback_storage_mixin
from . import resources
from . import ai
from . import submissions
from . import aps_assign_students_wizard
from . import aps_dashboard
from . import core
from . import res_users
from . import hr_employee
from . import hr_resume_line
from . import conditional_views
from . import res_partner
from . import aps_partner_voting_token_wizard
from . import awards
from . import asc_timetable
